const tealcar =
`xxxxxXXxXXXXXXxXXXxXXXXXxXxXXxxXXXXXxXXXXXxxxxxxxxXxx+xxXXXXXxXxXXxxXXXxxxXXXXXXXXXXXXXXXxxxxxxxxXxxxxxxxxxxxxxxxxx+x+xxxx++xxxx+xxxxxxXXxxx+;xx++xx+x++x+xx+++++x+++++X+x++xxxxx+;;;;+;++x+xxxx++Xx+++xXxxxxx+;xxxxxxxxXxxxX+xxX++++++x+xXxX$x++XxX++XXx++Xx+XXXXXxxxxxxxxxXXXXX$$$$$$$$X$$$$$$$$$$$$X$$XX$X$X$X$$XxXx$$$$$$$$$&X$XXXXXXX$XXXXX$X$$X$X$$$X$X$XX$$X$$$XXXXXXX$XX$$$$$$$$$$$$$XXX$XXXXXXX$X$$$$$$
xxxxxXXxxXxXXXXXXXxXXXXXXXXXXxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$XXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxXXxxxXXXXXXXxxxxxXxxxXXxxxxXXXXxXXxxxXxXXXXXXXXXXXXXXXXXXXXXxXxXXXXXXXXXXXXXXXxxxxXXXXXXXXXXXXX$X$$$$X$XXXXX$XXXXXXXX$$$XXXXXxXXXXX$$$XXXX$XX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$&$$$$$$$$$$XXXx$$$$$&&$&$$&&$$X$$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
xxxxxxXXxxXxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxXXXXXXXXXXXXXXXXXX$$XXXXXXXXXXXXXXXX$$XXXXXXXXXXXXXXxxxxxxXxxxxxxXXXXxxxxxxxxxxXxxxxxxxxxxxxxxxxXXXxXxxXxxXXXxXXXxXXxxxXXxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$X$XXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxXXXXXXxXXXXXX$XXX$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$&$$$$$$$$$$XXX$$$$$$$$$$$$&$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XX$$X$$$$$$$$$$$$$$
xxxXxxXXxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$XXXXXXXXXXXXXXXXXXXxXXxXxxxXxxxxXxxxxxxXxxxxXxxxxxxxxxxxxxxxxXxxxxXXXXXXXXXXXXxxXXXXXxxxxXxXxxxXxXxxXxXXXxXXXXXXXXX$X$X$XXXXXXXXXX$$X$XXXXXXXX$XXXXxxxxxXXXXXXXXXXXXXXXXXX$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X$$$$$$$$$&$$$&&$$$$$$$$$$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
xxXXXXXXxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxXxXXXxxxxXxXXXXxxxxxxXxXXXxXxxxXxXXxxXxXxXXXXXXXXXXXXXXXXXXXXXXxxxxXxxxxxxXXXXXXXXXXxXXXXxXxxX$$$$XXXXXXXXXXX$XXXXXXXXXXXXXXxxxXxX$XXXXXXXXXXXXXXXXXX$$$&$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$&&&&&$$$$$$$$$XX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXxX$$$$$$$$$$$$$$$$$
xxxXXXXXXXXXXXXXXXXXXXXXXXXX$X$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$XXXXXXXXXXXXXXXXXXXXXXXXXxXXXXXXxXxxxxxxXXXXXxxxxxXXxxXXxxxxXxXXxxXXxXXXXXXXXXXXXXXXXXXXXXXXxxxXXxxxxXXXxXXxXXxXXXXXXXxxXXXX$$$$XXXXXXXX$X$XXXXXXXXXXXXXXXxXXXXXXXXXXXXXXXXX$XXXX$XX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X$$$$$$$$$$$&$$$$$$XXXXXXX$$$$$$$$$XX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XxXXxXX$$$$$$$$$$$$$$$$
xxxxXXXXXXXXXXXXXXXXXXXXX$XXXXXXXXXXXXXXXXXXXXXXXXXXXXxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$XXXXXXXXXXXXXXXXxxxxxXxxxxXXXxXxxXXXXXXXxxxxxXXXxxxxXXxXXXXXXXXXXXXXXXXXXXXXXXXxXXxxxxxxXxxxXXXXXXXXXXXXXXXX$$$$$XXXXXXXXX$X$XXXXXXXXXXXXXXXXX$XXX$X$X$XXXXX$XXX$$$X$$$$$$$&$$$$$$$&$$&$&$$$$$$$$$$$$$$$&$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXX$XX$$$$$X$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXX$$$$$$$$$$XXXxxXX$$$$$$$$$$$$$$$$
+xxx+xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxXXXXXXXxxXXXXXXXXXXXXXXXXXXXXX$XXXXXXXXXXXXXXXXXxXxxxxxxxxxxXXxxXxxxXXXXXXXXxxxxXxxxxXxxXXXxXXXXxXXXXXXXXXXXXXxXXXxxxx+xxxxxxXXXXX$XXXXXXXXXXXXXX$X$XXXXXXXX$X$$XXXXXXXXXXXXXXXXXXX$$$$$$$XXXXXXX$$$$$$$$$$$&$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$&$$$$&$$$$$$$$$$$$$$XXXX$$$$$$$$$$$$$$$$$$$$$$$$$$X$$$..:::::....+XX$+XXXXXXXXxxx+$$$$$$$$$$$$$$$$
xxxxXXxxx+xXxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxXXXXxxxxxxxxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxXxxXxXXXXxXxXXxXXXXXXXXXXXXxxxxxxX+xxxXXXXxxXXXxXXXXXXXXXXXXXXXXXXxxXxxxXXXXXXxXXXXXXXXXXXXXXXXXXXX$$$XX$$XXXXXXXXXXXXXXXXXXXXXXX$$$$$$$$XXXXXXXXXX$$$$$&$$$&&$&$&$$$&$&$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$&$$$$$$$$$$$$$$$$$$$$XXXXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X$.::::+;;:::.XX$:XXXXXXXX++Xx$$$$$$$$$$$$$$$$
xxxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxXXXxxxxxxxxxxxXXXXXXXXXXXXX$XXX$XXXXX$$$$$XXXXXXXXxxxxxxxXXXXXXXXXXXXXXXXXxXxXxXXXXxXXxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxXXXxxXXXXXX$X$XXXXXXXX$XXXXXX$$$$$$$XX$XXXXX$XX$X$XXXXXX$$$$$$$$$$XXXXXXXX$$$$$$$$&$$$$&$&$$&$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XX$$$$X&$$$X$$$$$$$$X$$$X$...::::::;;:XX$.XXX$XXXXxxxX$$$$$$$$$$$$$$$$
xxxxxxXXXXXxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxxXXXXXXXXXXXXXXXXXX$$XXXXXXX$$$$XXXXXXXxXxXXXxXXxXXXXXXxXXXXXXXXXXXXxxxxxxxXxXXXXXXXXXXXXXXXX$XXXXXXXxXXXXxxxxxxxXXXXX$XX$XXXXXXXXXXXXXXXX$$$$$$X$$$$X$X$$$$X$$$XXX$X$$$$$$$$XXXXXXXXX$$$$&$$$$$$$$$&$$$$$&$$$$$$$$$$$$$$$$$$$$$$$$$$$$&$$$$$$$$$$$$$$$$$$$$$$$$$$$$X$$$$$$$$X$$$$$$$$$X$XX$$XXXX$$X......::::;;;XX$.XX$XXXX$$$X$$$$$$$$$$$$$$$$$
xxxxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$XX$X$$X$XXXxxXx$$$Xx+$XXxx+;+XXXXXXXXXXXXXXXXxXxXxxXxxXXxxxxxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxXXX$XXXX$$XXXXXXXXXXXXXXXXX$$$$$$$$$$$$$$XX$$$$XXX$$$$$$$$$$$$XXXX$$$$$$$$$$$$$$$$$$$$$$&$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$&$$$$$$$$$$$$XX$XX$$$$$XXX$$$$$$$XXXXXXXXXXXXXXXXXXXXXXXXXxXXXX$:XX$XXXX+xXxX$$$$$$X$$$$$$$$$
xxxxxXXXXXXXXXXXXXXXXXXXXXXXXX$XXXXXXXXXXXXXXXXXXXXXXXXXXX$XXXXXXXXXXXXXXXXXX$XXX$$XXxx$X$+X$$$$$$XXXXXXXXXX++;$XXXXXXXXXXXXXXXXXXXXXXXXXXxXXXXXXXXXxXXXXXXXXXXxXXXxxxxxxxxxxXXXXXX$$$$$X$XXXXXXX$XXX$XXXXX$$$$$$$$$$$$$X$XXX$$$X$XX$$$$$$$$$X$$$$$$$$$$$$$$$$$&$$$&&&$&$$$$$$$$$$$&$$$$$$$$$$&$$&$$$&$$$&$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXXXXXX$XXX$XXXXXXxXXXXXXXXXX+XX$XxxXx$xxX$$$$$$X$$$$$$$$$
xxxxXXXXXXXXXXXXXXXXXXXXXXXXXXX$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$X$$X$$$$$X;X$$$XX$$X$$$$$$$$$$$XXXXXXX$+XXXX$$$$$$$$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxXXxxxXxxxxXXXXX$$XXX$X$XXXXX$XXXXXXXXXXXX$$$$$$$$$$$XXXXX$XXXXXXXXXXX$$$$$$$$$$$$$$$$&$$&&$&&$$&&&&$$&&&$$$$$$$$$$$$$$$$&$$$$$$$$$$$&$$$$&$$$$$$$$$&&$$$$$$$$$$$$$$$$$$$$$$$$$XXXXX$XXX$XXXXxXXXXXXXXXXXX$XXXXXXXXXXXXXXxx+$Xx+x$$$$$$$$$$$$$$$$
xxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$$$$$$$$$$+xxx$$$$$$$$$$$X$$$$$$$$$$$$X$$$$$$$$$$$$$XXXXXXXXXXXXXXXXXXXXXXXXXX$XX$$X$$XXXXXXxxXXXXxxxXXXXXXX$$$$$$XXXXXXXXXXXXXxXXX$XX$$$$$$$$XXXXXXXX$XXXXxX$$$$$$$$$$$$&$$$$$$$&$$&&$&$$$&&&&&$$$$$$$$$$$$&&$$$$&$$$$$&&$$$$$$$&$$$$$$&$$&&$$$$$$$$$$$$$$$$$$$$$$$XX$$XXXXXXXXXxXXxX+xx+xxxx+xxxxxXxxxxXxxxxXxXXX;x++&++x$$$$$$$$$$$$$$$$
xxxxXxXXXXXXXXXXXXXXXXX$$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$$$$X$$$$$$X$$$$x;$$$$$x++$$+XX$$$$$$$$$$;;$$$$$$$$$$XX$;XXXXXXXXXXXXXxXXXXXXXXXXX$$$$$$XXXXxxxxxxXxxXXXXXXXX$X$XXXXXXXXXXXXXXXXXXXX$$$$$$$$$$$$XXXXXXXXXXXX$$$$$&$$$$&$$$$$$$$$$$$&&$&&&&&&&&$$$$$$$$$$$$$$&$$&$$$$$&$$&&&&$&$$$$$$$$$$$$$$$$$$$$$$&&$$$$$$$$$$$$$$XXX$$xXxXXxXxxxxX+++++++xxxx+++xXx++x+++++++:Xx+;;+:+x+x$$$XXX$$XXX$$$$$
xxXXXXXXXXXXXXXXXXXXXX$XXXXXXXXXXXXXXXXXXXXXXXXX$XXXXXXXXXXXXXXXXXXXXXXXXX$X$$$$X$Xxx:$X$$$$$$$$$$$$X$+;x$XXX$$$XXXXXXXXXXXXXXXXXXXXXX$X$XXXXX$$$XXX$$$$X$$XXXXXXXXXXXXXXXXXXXXX$$XXXXXXXXXXXXXXXXXXXXXX$$$$$$$$$$XXXXXXXXXXX$$$$$$$$$&&$$&&$$$&&&&&&$&&$&$$$&$&$&$$$$$&$$$&$&&&$&$$$$$&&&&$&&$&$&$$$$$$$$$$$$$$$$&$$&$$&$$&$&&$$$$$$$$$$XX$$xxXxxxxx++;:XXx;;;;;;+x+++;xX;+X+;;;;;+;;;;;:+:;+++XXXxxxXXXXXXXX$X
xxXXXXXXXXXXXXXXXXXXX$X$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$$$$$$$$X$$$$x;$XX$XXXXX++XXXXXXXXXXXXXXXXXXXXXXXXX$X$$$$$$$$XXX$$$$$XXXXXXXXXXxxxxxxXXXXXXXXXXXXXXxxXXXxXXXX$XXX$XXX$$$$$$$$$XXXXXXXXX$$$$$$&$$$$$$$$&$$&&&$&&$&&&&$&&$$&&$$$$$$$$$$&$$$&$$&$&$$$$&$&&&$&$$$$$$$$$$$$$$$$$$$$&&$$$$&&$&&$$$&$&&$&&$$XXX$Xx:::;+++;;;;;;;:;;;:::+;;;:;x;;;;;;;;;;+++;;:+::;;;XXxxxxXXXXXXXXXX
XxXXXXXXXXXXXXXXXXXXXX$XXXXXXXXXXXX$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$X$$$+XX$$$x$X$$$X$XXXXXXXXxXXXxXXXXXXXXXXXXXXXXXXX$$XX$$$$$XX$$XXXX$$$XX$XXX$XXXxXXxXXXXXXXX$XXXXXXXXxXXXXXXXXXXXXX$X$$$$X$$$XXXX$$$$$$$$$$$$$$$$$$$$$$&$$$$$$$&$&&&&$&$$$$$$$$$$$$$$&$$&$&&$$&$&&&$$&$$$$$$&$$$$$$$$$$$$$$$$$$$$$&$$$&&&&&&&&&&&&&$&X$$Xx$$xxXXXXXXxxxxxx+++:+x;+++;+;+xx+xx+:;+XXXxX;;:+:::;:xxxXxXXX$$XXXXXX
XxXXXXxXXXXXXXXXX$$$XXX$XXXXXXXXXX$$$XXXXXXXXXX$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$XxX$$$XXXX$XXX+;xXXXXXXXXXXXXXXXXXxXXXXXXXXX$$$X$$$$$$$$$$$$$$$$$$$XXXXXXxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$XX$$$$$$$$XXX$$$$$$$$$$$$$$$$$$$$&$&$$$$$$$$$$$$$&$$&$$$$$$$$$$$$$$$$$$&$$$$$&$$&$$$$$$$$$$$&$$$$$X$$$X$$$$$$$$X$$$$$$$$$$$$$$&$&&&&&$XXxx+x+;;++++;;+.....;;+;::;;;++;;:.;+;;;:;+xxxx:X:;;:::::xxxX&+X;$$XX$x;x
XxxXXXXXXXXXXXXX$$$$XXX$XXXXX$X$XX$$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX;++x$$$XX$$$$XXXXXXXXXX;XXXXXXXXXXXXXXXXXxXxXXXX$XXxx$$$$$$$$$$$$$$$$$$$XXXXXXxxxXXXXXXXXXXXXXXXXXXXXXXX$X$$$$$$$$$$$$$$$$$&$$$$$$$$$X$$$$&&$&$&$$$$&&&$&&$&$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X$XX$X$X$$X$X$$$$$$$$$$$$XX$XXXXXX$$$$$$X$$$$$$$$$$$&$&&&$&$$+++;;::::;;;;::::;;::::::+;::;+;;+;:;::+;;;++++;++XX;::::+x$+x$$X;XxXxXXxx
xXXXXXXXXXXXXXXX$$$X$$$$XXX$X$$$XX$$XXXXXXXXXXXXXXXXXXXXXxXXXXXXXXXXXXXXXXXXXX$XXXXXXXXXXX$$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxXXXXXXXXXX$X$$$X$$$$$$$$$$$XXXXXxXxxXXXXXXXXXXXXXXXXXXX$$$X$XX$$$X$$$$$$$$$$$$$$&$$$$$X$&&$$$$$$$$&$&&&&&&&&&&&&$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXXXXXX$$$$$$$X$XXXXXXXX$$XX$$$$$$$$$$$$$$$$$$$$$&$$&$:;;:::::::::::::::.::::;;:::..::.;:::;:::::;+;:++:++++.+++:++x+xXXxx+.$XXX
xXXXXXXXXXXXXXXX$XX$X$XXXXX$$$$X$$$$X$$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX+++;XXXXXXXXXXX$XXXXXXXXXXXx+++XXXXXXXXXXXXXXXXXXXXXXXXXXXXX$X$$$$$$$$$$$XXXXXXXXXXxxX$X$$XXXXXXXXXX$XXXXXX$$$$$$$$&$&$&&&&$$$$$&$&$$X$$$$$$$&$$$&$$$&&$$$&$&$&&$&&&$$$$$$$$$$$$XXX$XXXX$X$$$$X$XXXXX$X$XXX$$$XXXXXXX$$X$X$$$$$X$$$$$$$$$$$$$$$$$$$$$$$$$$&:::::::::::::::::::.........::::::::::;;::::::;::;;;;;;;;;+++++:xx++++xX$X
XXXXXXXXXXXXXXXX$$XXXXXXXXX$$$$$X$$X$$$XXXXXXXXXXXXXXXXXXXXXXXXXXX$XXXXXXXXXXXXXXXXXXXXXXXXXXxXXXXXXXXXX+;XXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$$$$$$$$$X$XXXxXXXXXX$X$$$XX$$XXXXXXXXXXX$XX$$$$$&$$$&$$$&$$$$$$$&$$$&X$$$&&$$$$$&&&$$&&&&$$&&&&&$&&$$$$$$$$$$$$$$$$X$XXXX$$$$X$X$XXXXXXXXXXXXXXXX$XXX$$$$$$$$$$$$$$$$$$$$$$$$xx$$$$$$$$$$$$:::;;:::::::::::::::.......:::.:.....:::;;;:::::;:::;::;;;;;++++;++++:xxxx+
;++++x+++;xXXXX$XXXXXXX$XXXXXXXXXX$XXXX$XXXX$$XXXXXXXXXXXXXXXXXXX$$$XXXXXXXXXXXXXXXXXXXXXXXxxxXXXXXXXXXXXXXxXXXXXXxXXXXXXXXXXXXXX$$XX$$$$$$$$$$$XXXxxxXxXXXXX$X$X$$$X$$$XXXXXXXXX$$$$$$$&$$$&$&$$$$$$&$$$$$$$;$$$&$&&&&&$$$&$&&&&&&&&&&&&&$&&$$$$X$$$$$$$$$$$$$XXXXXXXXXXX$$XXXXXXXXXXXXXXXXX$$$$$$$$$$$$$$$$$$$$$$$$x++;$X$$$$$$$$$$$::;::::::;:::::::::.............:.....::::.::.:::::::;;;;;;;++++++++:+++xx
Xx+;::;+;;;;xxX$XXXXX$$$$$X$$$XXXX$$$$$$$XXXXXXX$XX$XXXXXXXXXXX$$$$$$x++xXXXXXXXXXXXXXXXXXXXXXXxXXXXxXxXXXXxXXXXXXXXXXXX$XXXX$$$$XX$$$$$$$$$$XXXXxxxxxXXXX$$$$$$$$$XXXXXXxXXX$$$$$$$$&$&$$$$$&&&$&$$&&$$$&X+&$$$$&&&$&&&&&&&&&&&&&&&&&&&&$&$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXXXXXXXXXXXXXXXX$$$XX$$$$$$$$$$$$$$$$$$$$$$$$+++$X$$$$$$$$$$$&:::::::::.:.::..::.......................::::::::::::;;;;;;;;;;;;:+:+++++x
xxxxXXXXXXXXXXXX$XXX$XX$XXX$$$XXXX$X$$$XXxxXX$X$XXXXXXXXXXXX$XX$$$$X$$XXXXXXXXXXXXXXXXXXXx$XXxXxXXXxxXxxXxXXXXXXxXXXXX$$$$X$$$$$$$$$$$$$$$XXXXXXxxXXXX$X$$$$$$$X$XXXXXX$$$$$$$$$$$$$&$$$&$$&&&$$$$$$$$&&++$&&$$$$&&&&&&&&&&$&&&&&$&&$&&$$$$$$XX$$$$$$$$$$$$$$$$;;+;x+;+;x;+:x:+;;+;;:;:::::::::::::::::::;;:;::;+;++;:++XxX$XX$$&&&X&$;..::;::......... ..... . .... .......:.....:::.:::..::::::;;;;;;;:;;+++++
+xxxx+xxxxXXxxXXXXXX$$$$$X$$$$$$$X$$$$$XXXX$$$XXXXXXXXXXXXXX$$$X$$$$$X$XXXXXXXXXXXXXXXXX+x$XXXxXXxx+xxXX$+;XXX$X$$$$$$$$$$$$$$$X$$$$$XXX$XXXxxXXXXXXX$$$$$$$X$XXXXX$$$$$$$$$$$&$$$$$$$$$$$$&$$$$$$&$&&xx$$&&$$$$&&&&$$$&$&&$&&&$$$&$$&$$$$$$$$$$$$$$$$$$$$$$$XXXxx$$;++xx;x+X:+:x+xX:++++xxxxxxxxxxxx+++;;x++;xx+++x+xx+;+x+x+xX:x+xX+++X+x++xx+x;xx++xx+$$$$$$X$$$$x$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XX$$$$$X$$$$$$
xxxxXXXxXX$XXXxX$$$$$$$$$X$$$$$$$X$$X$$$XX$$$XXXXXXXXXXXXXXXXX$X$$xXxx+XXXXXXXXXXXXXXXXXX$$X$$xxxx;xxXX;X$$$$$X$$$$$$$$$$$$$$$+X$$$XXXXXXxXXXXX$XX$$$$XXXXXXXX$$$$&$$$$$$$$$&$$&$$$$&&&$&&$&$$$$&$&&XX$$&&$&$$$$$&$&&&$$&$&&&&$$$&$$&&$$&$$$X$$$$$$$$$$$$$X$$XXxXxX$;:XXXXXxX+++;;;x+;;+xxx++++++++xxxxx++x+++xxx;;+xx;+;x+;;;xx+x:+++:+;;+;;X+++xxxx;xxx$$$$$$$$$$$&$$$$$$&$$$$$$$$$$$$$$$$$$$$$$$$$x$X$X$$$$$$
XxxXXXXXXXXXXX+X$X$$$XX$XX$$$$$XXX$$$$$$$XXXXXXXXXXXXXXXXXXXXXXX$$$$XXXXXXXXXxXXXXxxXXXXXXXXxx+xxx+xX$$XX$$$$$$$$$$$$$x$$$$$xxX$$$$$$$$X$XX$$$$$$$$$XXXX$$$$$$&$$$$$$$&$$$$$$&&$$&$$$&$$$&$$$$$$$;$&&$&$$$&&$$$$$$&&&&&$$&&&&&&$$$$$$$$$$$$$$$$$$$$$$$$$$$$X$XXxx+x+x+X$XXXXXXXXX$XXxX;;;;+;;;;;;+++++++;+xxxxxx+;;;;+;;;+;;;;;;;;;;+++xX+XX;;+++;;;;;;;+$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$xXx$$$$XX
XXXXXXXXXXXXXX$X$$$$$$$$X$$$$$$$$$$$$$$$XXXXXXXXXXXXXXXXXXXXXXXX$$xXxxXXxXXx++XXXXXXXXXXXXx++xxxxx+Xx;$$X$$$$$$$$$$$$$$$$$$x$$$$$$$$$$$$$$$$$$$$XXXX$X$$$$$&&&$&$&&$$&&&&&$$$$$$$$$$$&&&&$&$$$&&x&&&$$$&$$&$&$&$$&&&&&&&&&&&$$$$$$$&&$$$$$$$$$$$$$$$$$$$$$$XXX;xx$XxXX$$$xXXx+++XXXXXx;;+++;+;;;;;;;+++;;+xxxXxx+;;+;+++;;;;;;;;;;;;:xx$xx+$++++++xXXXXXx&$$$$$$$$$$$$$&$X$$$$$X$$$$$$$$$$$$$XX$$$$$$$$$XXX$$$$$
XXXXXXXXXXXXXX$X$$$XX$$$$X$$$$$$$$$XX$$XXXXXXXXXXXXXXXXXXxXXXXXX$$$xx++x++++xxXXXXXXxXX+xxx+xxxx+X+X$$X$XxX$$$X$$$$X$$$$$X&$$$$$$$$$$$$$$$$$$$$$$$$$$$$&$$$&&&&&$&$&&$$$$$$$$&&&$$&&&$$$$$$&&&x&$$&$$$$$$$$$$$&$$&&&&&$&&&&&$$$$$$$&&&&$$&$$$$$$$$$$$$$$XXXXXX;xxxxx;;+++XX+xXXXXXXXXx+++x;;+++;xX;;+;+;;+X+xxxx+;x;x+;;+;;;;;;;:+$$$X$$$xXX+Xx++X+x$$$$X$$$$$$$$$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XX$$$.$XX
XXXXXXXXXXXXXX$X$$$$$$$$X$$$$XXXX$$XXXXXXXXXXXXXXXXxXXXXXXXXXxXXXXXX+++xx++xxxxx+xxxxxxxxxx+xx++x+$XXXxxXXXXXXXXXXXXXXXxXXXXXXXXXX$$$$$$$$$$$$$$$$$&$&&$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X$$$$x$$$$XXX$$$$$$$$$$$$$&$$$$$$$$&&$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXX$+xxx$$xxXx+;xxXXxXxxxXXX;;++;;++;Xx;;;+;+;;+XxXX+++;;;;;;;+;;;;;;;;$XxxXXXXX;x++X&;$$&&$$$$$$$$$$$$$$$$$$$$$$$$$$$$X$$X$$$$$$$$$$$$$$$$$$$$$$$XX$$
XXXXXXXXXXXXXXXXXX$$$$$XX$X$XXXXXXXXXXXXXXxXXXXXXXXXXXXxxxxXxXXxx+++xx+++x+xxx++xxxxxxxxXxxxx+xXXXxXxx;xxxXXXxXxXxxXXxXXXXXXxxxxxxXXXXXXXXXXXXXXXXX$$$$$$$$$$$$$$$$$$&&$$$$$$&$$$$$$$$$$$$X$$$$$$$$$$$XXXXX$X$$$X$$$$$X$$$X$X$$$$$$XXX$$$$$$X$$XXX$$$XXXXX$$$;+x+x+x;+++;+xXxxX++xx+XX;;;;;+;+;xxx;;+++;;+xx+x+++;+;;+;;+;+++++++$X$$&&XX$xX;:$&xX$&$+x:$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
xxxXXXXXXXXXXXXXXXXXX$X$XXXXXXXXxXXxXXXXxxxxxxxxxxXXxXXxxxxxxXxXXxXxxx+++xxXxxxxxxxxxxxxxxxXXxxxXXxxXXXxxXXXXXxXXXXxxXXXXXXXXXxXXXXXXXXxXXXXXXXXXXXX$$$XX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$x$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X$XX$$$$XXXXXXXX;+:$$$X+xxXXX.+;;;:xx$+xx+;++;;+;;+$xxxX:++;;+++++++++xxx$Xx++;x++xxx$XXxxXXX;xx+XX&$+&&$X&X+&$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X
xxxXXxxXxxXXXXXXXXXXXXXXXXXXXXX$xXXxxXXxxxxxxxxxxxXXXxXxxxxxXXXXXxx;xxx;;xxxxx+x+xxxxxxxxxX+XXxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxXXXXXXxxxxxXxxxxxxXXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$+.X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X$$$$X$XX$$$XXXXXXxX;xxx$XX$$xxxXX;;;X.:xXXXXXx;;;;;+;++xXXxxXX;;++xxX+++x+x+x$$$X+;;;;xXX+;XXXXx++XXXXx+$xX&&$&$XX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XX
xxxxXxxXxXXXXXXXXXXXXXXXXXXXXXXXxXXxxXXxXxxxxxxxxxxXXXXXxxxxXXXXXXxXxxxxXXxxxxx+xxx+x+xxxxXXXXXxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$X$$$$XxxxXxXXxxX$$$$$$XXXXXXX$;XXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$&$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$:;+XX+XX$X$:;:+;+;+xX+XXXx++x:;++;+;+++xx+x+X++;;xXx+x+x+xx++&X$Xx$+$XXX++X$+;X;+xxxXxX+&&++&x+X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X
xxxxxxxXxxXXXXXXXXXXXXXXXXXxXXXXxXXXXXXxXXXXXXXXxxxXXXXxxxxxXXXXxXx+++xxx+;x+xxxx+++xXxxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$$$$$$$$$$$$$$$$$$$$$$$$XXXX$XXXXXXXX$$$$$$$X$$$$$$$$$$$$$$$$$$$$$$$$$$&&$$&$$$$&$&$$$$$$$$$$$$$$$$&$;++$$$x$XXXX:;;x+x+X:;;;xx+++x;;;+;;+X;xXXxx;++X;+x+X+xxXxxXx$$$$X.;xx++:+;X++++++xxXXxxxx&XxXXx;&$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$&$$$$$$$$$$$$$$$$$$$$$X
xxxXxxxxxxXXXXXXXXXXXXXXXXXXXXxXxXXxxXXXXxxxXxxxxxXXXXXxxxxxXXxXXXxxxxxxx;++++xxxXxxxXxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$$$XXXXXXXXXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXX$$XXX$XX$$$$$$$$XXX$$$$$$$$Xxx$$$$$$$$$$&$$$$$$$$$$&$$$&$$$$&$$$$$$&$X+$$$$$xxX$Xx++;++xX&$X$;+x+++x;;;;;;;x;$XXXXX$xx;+XxX+XxXxxxX$$XxxX+Xx$Xx+:xx&X;x;xxXXxxx+X+xXX$x$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XX
xxxxxXxxxxXXXXXXXXXXXXXXXXXxXXXXXXXxxXxxXXXxXxXxxxXXXXXXxxxxXXXXXXxxxxxxxxxxXxxxxxxXXxXxxXXXXXXXXXXXXXXXXXXXXXXXXXX$XXXXXXXXX$XXXX$$XXXX$XXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXX$$XXXXXXXX$$$$$XXXXXXX$$X$$$X &$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$&xX+$$$$$$X++;+;X&+xXX$:x;;+$$++++;+;;;;;xx$$+x$X$+X;+XX+++xx++x$$$X+.+++XXX+X:X$$$$;+xx+X;xX&&$$$&Xx$$$$$$$X$$$$$$$$$$$$$$$$$$$$$$$$$$&$$$$$$$$$$$$$$$$$$$$
xxxxXXxXXXXXXXXXXXXXXXXXXXXXXXXXxXXXXXXXXxXXXxxxxxxxxXXXxxxxXXxXXXxxxxxxxxxxxxxxxXXXxxxxXXXXXXXXXXXXXXXXXXXXXXXXXX$$$XXXXXXXX$XX$XXXXXXXXXXX$$XX$$$$$$$$$$$$$$$$$$$$$$$$$X$XXXXXXX$XXXXXXX$$$$$$XXXXXXX$XX$$X$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$xxXXX$$$$$$$$++++xx++Xxx++x+++X$$X++;;;;;;+x$$$x$$$$+X;&x;xxXx+XXXX$$;Xxxx+xXXX;$X+xX$x$X$$Xx;XXX$$$$Xx$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XX
xxxXxxxXXXXXXXXXXXXXXXXXXXXXXXXXxXXXxXXXXXxXXxxxxxxxXXXXxxxxXXxxXXxxxxxxxxXxxxXxXxxxxXXXXXXXXXXXXXXXXXXX$X$XXXXXXX$$$$XX$$XXXXXXXX$XXXXXX$$XX$XX$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXX$$$$XXXX$XXXxXXxxXXXXXXXXXX$X$X$XX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$x+x+$$$$$$$$$X+xx$XX$$$$$Xx++xx;X$X+x;;;+;+++$$$$$$$$xX;;;X;;+X$$Xxx+xx$$&$x$+xxx..Xx+$$X$xX$+++;xx&$$XXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X
xxxxxxxXxXXxXXXXxXXXXXXXXXXXXXXXxXXxXXXXXXxXxxxxxxxxxxxXxxxXXXXXXXxxxxxxXxxXxxXxxXxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$$$$X$$$$XXXXXX$XXXXX$$$$$$$$X$$$$$$$$$$$$$$$$$$$$$$XXXXXXXX$X$$$$XxXxxXxXxxxxXXXXXXXXXXX$X$XX$$$$X$$X$$$$$$$$$$$$$$$$$$$$$$XxX$$$$$$$$$$$$+xxx$XXxX$x$xx$;X+xxxx+;;;xxxx&X$$$$$$xX++;;;;;;;+;x++++xXxx++$;+Xx...$$xxxx$$$$X$x+$XXX+;$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X$
xxxXxxXxXxXxXXXXXXXXXXXXXXXXXxXXxXXXXXXXXXxxxxxxxxxxxXxXxXxxXXxXXXxxxxxXXXXxxxxxxxXxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$$$$$X$$XXXXXXX$XX$X$X$$XX$XX$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXXXXXXXXxxXxxXXXXXXXXXXXXXXXX$X$$$$$$$$$$$$$$$$X$$$X$$$$$X$$$$$$$$$$$$$$$$$$$$X++Xx$$$;+XX$$$$+$+;++;:;;;XXXXX$+xxx+x$$+++;;;;;;:;+xxxxxxxX$$$$XX$$$&$x;x:++xXx;:X+X$$$+;&$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X
xxxxxxxxxxXXXXXXXXXXXXXXXXXXXxXXxxXxXXXXxxxxxxxXxxxxxxxXxXXXxXXXXxxxxxxXxxxxxxxxxxxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$$XXXXXXXXXXXXX$$$$XXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXXXXXXXXXXXX$XX$XXXXXXXX$$$$$$$X$$$$$$$$X$$$$$$$$$$$$$$$$X$X$$X$$$$$$$$$$$$$$X$;X$$XXX$$$X$x++X++xx::;;;;;x$xXX$$$$$X&;;;;+;;;;;:;;+xx+++x++++++XXxxx$+X$X++x+xXXX$$X+;;$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X
xxxxxXxxxXXXXXXXXXXXXXXXXXXXXXxxxXXxXXXxxxxxxxxxxxxxxXXXxXXXXXXXXxxxxxxxxXxxxxxxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$$XXXXXXXXXXXX$$$XXXXXXX$$$$$$$$$$$$$X$X$XX$$$$$$$$XXXXXXXXXXXXXXXXXXXXXXXXXX$+++XxxXXXXXXXX$$X$$$$$XXXXX$$$$$$$$$$$$$$$$$$XXXX$$$$X$$XXXXXxXx+;x&XXXXXXXX$XXXxx;.::;;;;+;X++xxxx+x;+;+++;;;+;;;;;++++++++++x+$XX+XX;+X$XXXx$XXXXX+x+:$$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X
xxxXxXxxXXXXXXXXxXXXXXXXXXXXXXxxxXX++x++++++xx+++++++++xxx+xx++x++++++++x+x+xx+xxxXxxxxxxxXXxXXXxxxxXxxxxxxXXxxXXXXXXXXXXXXXXXXX$$$$X$$$$$$$$$$$$$$$$$$$$$$$X$X$$$$$$$$$$XXXXXXXXXXX$XXXXXXXX$$XXXXXXXXXXXXXXXXXXXXXXXxX$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXXXXXXX;++XXXXxx+XXXXx+XXXx++::;;;;;;+x;;;++;;;;+++++++;++;;+;+++++++xxxxx$$XX$$;x$XXX$+XxxxXXX+;:$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X
xxxxxxxXxxXxXXXXXXXXXXXXXXXXXxxXxXXx+++++++x+++++++++xx+++++++++++++xx++xxxxxxXXxXxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxXXXXXXXXXXXXXXXXXXXXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXX$XX$$XXXXXXXXXXXXXXXXXXXXXXX$$$$XXXXXXXXxxxXxXxxXXXXXXXXXXXXXxxXXxXXXXxxxx;x+xXXxXxXXXXxx+++++++:.;;;;;;X+;;;;:++;++++;+++++++;;++x+xxxxx+++++x++XXXxXX$X$$$Xx+X;$+x:$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
xxxxxXXxXxXXXXXXXXXXXXXXXXXXXXXXxXxx++++++++++++++++x+++++++++xxxxxxxxxxxxxxxxXxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxXXXXXXXXX$$$XXXXXX$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXX$XXXXXXXXXXXXXXXxXXXXXX$$$$$$$$XXXXXXXXXXXXXXXXXxXXxXXXXXXXXXXXXXXXxxxxxXx;XxXX+++Xxx+++++++;;;;:.;;:;;x+;++x+++++++++++++++++;;;;;;++++++++++xxxXXXXXXXXXX$+;X$+Xxx:$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
xxxxxxxXXXXXXXXXXXXXXXXXXXXXXXXXxXXx+++x+++++++++++++++x+x+xxxxxxxxXxxxxxxxxxxxxXXXXXXXXXXXXXXXXXXXX$XXXXXXXXXXXXXXXXXXXXxxxXxxXxx$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXX$$$XXXXXXXXXXxxXXXXX$$XxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:+xXX;XXX+XXX$$$$X;++;;:;::;++;;;;++++++xxxxxxxxxx++;;;;+;;+;;;++++xxxxxxxxXxXX$$&+;$XXXx+;;&$$&$$$&$$$$$$$$$$$$$$$$$$$&$$$$$$$$$$$$$$$$$$$$$$$&$$
xxxxxxxxxXXXXXXXXXXXXXXXXXXXXXXXxXXx++++++x++++x+++++x+xxxxxxxxxxXxxxxxxxxxxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxx+xXXXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXXXXXXXXXXX$$$$XX$$XXXX$XXXXXXXXXXXXXXXXXXXXXXXXXXxx;XXXXXXXXx$$$$$$XX;;;:;;;;;;++;;;++++++++++++++x++++;;;;;;;;;;;;+++xxxxxxxxxXXx;++x+$$x:xx+$$&$&$X$$$X$$$$$$$$$$$$$&$$&$$$$$$$$$$$$$&$$$$$$$$$$$$X
xxxXxxXXXXXXXXXXXXXXXXXXXXXXXXxXXXX+++++++++++++++xxxxxxxxxxXxxxxxxxxxxxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxXX$$XX$XX$XXXXXXX$$$$$$$$$$$$$$$XXXXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X$XXXXXXXX$$$$$$$$$$$$$$$$$$$XXX$XXXXXXXXXXXXXXXXXXXXXXXXXXXXX+X+X$$+++XxxX;;;;;;;;+++;;;+++++++x+++++++++++++;;;+;;;;;;;;+xxxxXXXxxxxxxxxxxxX$$$+;x$$$$$$$X$$$$$$$$&$$$&&$$$$$$$$$$$$$$$$$$$$$$$$$$$$$&$$$
xxxxxxXXXXXXXXX$XXXXXXXXXXXXXXXXxXX+x+x++++++++++++xxxxxXXXxxxxxxxxxxxxxXxxxxxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$$XX$X$$$X$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXX$$X$$$X$X$$$$$$$$$$$$$$$$$$$$$XXXXXXXXX$$$$$XX$$$X$XXX$XXXX$$$$XXXXXXXXX$$$$XXXXXXXXXXXXXxxxXXXXXXXXXxxXX;;;;::++;;;;;;;;;;;;;;;;+++++;++++;;;;;;;;;;;;;;;++++xxxxxxxxxXX$$$$$$$x+$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$&$$$$$$$&$&$$$$$&$$$
xxxXxxXXXXXXXXXXXXXXXXXXXXXXXxXXXXX+x++++++++x+++xxxxxxXXXXxxxxxxxxXXxxXXXXXXXXxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$$$$$$$XX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXXXX$X$$$X$$$$$$$$$$$$$$$$X$$X$XXXXX$$$$X$XXXXXXXXXXXXXXX$XX$$XXXX$$X$XXXXXXXX$XX$$X$$$XX$XXX$XXX$$$Xx$Xxxxxxxx+Xxxxx++++XXx+x+x+x:XXx+x;x++++;;;;;::::;+;+;xxxx++xx+++x+;x$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$&&&$$$$$&&$&&&&&$$$
xxxxxxXXXXXXXXXXx$$XXXXXXXX+XXXXXxX++x++++++xxxxxxxxXXXXXXxXxxxxxxXxxxXXXXXXXXXXxXxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$X$$$XXX$X$$$X$$$X$$$$$$X$X$$$$$$$$$$$$$$$$$$XXXXXXXXXXXXXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXX$XXXXXXXXXXXXXXXXX$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXX$X$$$$$$$$:xXXxx$$$$$$$$$$$$$$$$$XX$$$$$XX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$&$$$$$&$$$$$$$$$$$$$$$$&&&&$$$$$$$$$$$$$$$$$$&&$&&&$&&$$&&&&&&$$
xxxxxxxXXXXXXXXXXXxx+XXXXXXXxXXxXXX+x++x+++++xxxxxxxxxXXXXxxxxxxxxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$X$XXXXXXXX$$$$$$$$$$$$$XXXXX$X$X$$$XX$$X$$$$$$$$$$$$XXXXXXXXXXXXXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXX$$XXXXXXXXXXXXXXXXXXX$$$$$$$$$$$$$$$$$$XXXX$X$$$$X$$$$$$$$$$X$$;+XXxx$$$$$$$$$$$$$$$$$$$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$&&&$&&$$&&&&&&&&&&&$&&$$$$$&$$&$$&$&$$$&&$$&&&&&$&&&&&$&&$$
xxxXxxxXXXXXXXXXX$xxXXXXXXXXXXXXXXX++xx+++x+xxxxx++xxxXXXXXxxxxxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$$X$$$$$XX$$$$$$$$$$$$$$$$X$$XXXXX$$$$$$$$$$$XX$XXX$XXXXXXXXXXXXXX$$$XXXXX$$$$$$$$$$$$$$$$$X$$$XXXX$$$$$$$$$$$X$XXXXXXXXXXXXX$$$$$$$$$$$$XXXXXX$$$$$$$$$$$$$$$$$$$$$$X+++xxx$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$&&$&$$$$$$$$$&&$$$$&&$$$$&&&&&&&&$&&&&&&&&&&$$
xxXxxxxXXXXXXXXXXXXXXXXXXXXXxXXXXxXx+xxx++xxxxxxXx+++++XxXXxxxxxXxXXXXXXXXXXXXXXXXxxxXXXxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$$$$$$$$XXXXX$$$$$XXXXXXX$$XXXXXXXXX$$$$$$$$$$$$$$$$X$$$$XXXXXXXXX$$$$$$$$$$$$$$$$X$$$$$$$$$X$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXX$$$$$$$$$$$XX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XX$$$$$$$$$$$$$$$$$$$$$$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$&&$$&&&&&&&&&&&&&&$$&&&&&&&&&&&&$
xxxxXXxXXXXXXXXXXXXXXXXXXXXXXXXXXxx+xxxx+++XxxxXXXx+++++xXxXxxxxXxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$X$$$$$$$X$$$$$$$$$$$$$$$$$XXXXXXXXXXXXX$$$$$XX$X$$$$X$$$$$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X$$$XX$X$$$&&$$&&$$$X$$$$$X$$$$XX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXX+xX+xX$&$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X$$$$$$$$$$&&&&&&&&&&&&&&&&&&&&&&&&$&&&&&$
xxxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXxx++xxx++xxxxXXXXXx++x++XXXXXXXxxxXxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxXXXXXXXXXXxxX$$X$$$$$$$$$$X$$$$$$$$$$$$$X$$XXXXXXXXXXX$$X$XX$X$$$XX$X$$$$$$$$$$$$$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$&$&&&&&&&&&&&&&&$$$$$$$$$$$$$$X$$$XX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X$;+;::::;;+;;xXXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$&&&&$$&&$&&&&&&&&&&&&&&&&&&&&&$$$
xxXxXxXXXXXXXXXXXXXXxXXXXXXXXXXXxxX+xxxx+xxxxXXXXXXXXXx+++xXXXXXXxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxXXXXXXXXXXxxXXX$$X$$$$$$$$$$$$$XX$$X$$$$$$XXX$$XXXXXXXXXXX$$$$$$$$XXXXX$$$$$$$$$$$$&$$$&$$$$&&$$&$$&$&&$$$&&&&&&$$$$$$$$$&&&&&&&&&&&&&&&&&&&&&&&&&$&&&$$&$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$...::;++++;;;;+xXXXx++x++;;;:;:+X&&$$$$$$$$$$$$$$$&$$&$&&&&&&&&&&&&&&&&&&&&&&&&$
xxxXXxXXXXXXXXXxXXXXXXxXxxXXXXXXxxX++xx+xxxxxXXXXXXXXXXxxxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$$XXXXXXXXX$$X$$$XXXXXXXXXXXXXXXXXXXXXXX$X$$$$$$$$$$$$$$X$$$XX$XX$XXXXXXXXXXXXXXXXXXXXXX$$$$$$$$$&$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$&&&&&&&&&&&&&&&&$&&$$$$$$$$$$$$$&$&&&&&$$$$$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X$$$$$$$$&$xxx;+++xxxxXxXXX$Xx;;++;;;;;xxx$&$$$$$$$$$&&&&&&&&&&&&&&&&&&&&&&&$$
xxxxx+xX$xXXXXXXXXXXXXxxxXXXXXXXXXX++x+xxxxxXXXXXXXXXXXXxXxxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$X$$$$$$$$$$$$$$$$$XXXXXxXXXXXXXXX$XXX$XX$X$$$$XX$XX$X$$X$XXX$$$X$$$$$$XXXXXXXXXXXXXXXX$$$$$$$$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$$&&&&&&&&&&&&&&$$$$XXXXXX$$$$$$$$$$$&$&&$$$$$$$$$$$$$$XXXXX$$$$$$$;:+xxXXXXXxxxxxx+++++xxXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$&$$$X+XX$XX$X$$$$X$$X$++;;;++++++x$$$&&&&&&&$$&&&&&&&$
XXxXXXXXXXXXXXXXXXXXXXxXXXXXXXXXXXx+xxxxxxxXXXXXXXXXXXXXXXXXxxXXXXXXXXXXXXXXXXXXXXXX$XX$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXXXXXX$XXXXXXXXXXx$$X$$$$$$$$$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$$$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$$XX$$&&&&&&&&&&&&&$$XXXXXXXXXXXXXXXXXxXX$$$$$$$$$$$XX$$$$$$$$$$$$$xx;;:.;x::;::.:::::::;;xx++xxXXXXxx$X$$$$X$XxX$$$$&&$$$$$$$$$$$$$$$$$$&XX....;xxXXX$$$$$$$XXXXXXxxx++:::::;;x.
xxxXXXXXXXXXXXXXXXXXXxxXXXXXXXXXxXx++xx+xxxXXXXXXXXXXXXXXXXXXxXXXXXXXXXX$$XXXXXXXXX$XXXXX$$$$$$$$$$$$$$$$$$$X$$XXXXX$XXXXXXXXXXXX$$$XXXX$XXX$X$$$$$$X$$$$XXXXXXX$$XXXXXXXXxx++;;;++xxxxxxXxXXXX$$$$$&&&$X$$&&&&&&&&&&&&&&&&&&$$$XXX$$$$&&&&&&&&&&&&$$$$$XXxxxxxxxxxxXxxxxxX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X$&$&$&&$x:..::.::;++xx+xx$XXXXXxxx+xXX$XXXX$$$$&$$$$$$$$$$$$$$$$$$$$$$$$$$&&&&&&&&&$&$$&&$$&&.
xxxXXXxXXxXXXXXXXXXXXxXXXXXXXXXXXXX+xx+xxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$XXXXXX$$XXXXXXXXX$$$$$$$$$$$$$$$$$XXXXXXXXXXXXXXXXX$$$$$$$$$$X$X$$XX$X$$XXXX$$X$X$$XXXXXXXXXx+++++x+;;;+;++++++xxxXxXXXXXX$X$$XXX$X&&&&&&&&&&&&&&&&$$$$$XXXX$$$&&&&&&&&&&&&&&$$$$$$XXXXXxxxxxxxxxX$$$$$$$$$$$$$$$$$$$$$$$$X$$$$$$$$$$$$$$$$$$x$$$$$$$$$$$$$$$$$$$&$$x...:;;+xXXxx+xxXXXXXXXXXXXXXXxX$$XXXXXX$&$$$$$&&&&&&&&&&$&$&$$$$$$
xxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxX+xxxxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXxXX$XXXX$$$XXXXXXXXXXX$$$$$$$$$$$$$$$XXXXXXXXXX$$$$$X$XX$$$$$$$$$$$$$$$$$XXXXXXXXXXXXXXXXXXxx++++++;;;::::::::::;;;;;;;+xxxXxXXXXXXXXXX$$&&&&&&&&&&&&&$$XXXXXXXXX$$&&&&&&&&&&&&&&&&$$$$$$$$$XXXXxxxxxX$$$$$XX$$$$$$$$$$$$$$$X$$$$$$$XXX$$$X$$$$X&$&$$$$$$$$$$$&$$$$$$$$$$$$&$$$&$$&&$++x.:+;+++xX$$++;x+++xX$XXXX$X$&&&$$$$&&&$&&$&xxxx+++x
xxxXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxXX++xxxxXXXXXXXXXXXXXXXXXXXXXXXXXXxXxxxX$XXXX$XXXXXXXXXXXXXXXX$XX$$X$XXXXXXXXXXXXXXXXX$X$$X$$$$$$X$X$XX$$$$$XXX$XXXXXXXxxxxx+++x+:::;::::::::::::;::;;;;;;;;;++xxxxxxXXXXXXXX$$$&&&&&&&&&$$XXXXXXXXXXXX$&&&&&&&&&&&&&&&&&&&&$$$$$$$$$XXXXx$$$$$X$$$$$$$$$$$$$X$$X$$$XXXXXXXXXX$Xx$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$&$$$$$$$$$$$$$$&&$x:...:;;++$$$X$$$&&&&$$&&&&&$Xxxxxxx
xxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx+xxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxX$$XXXXXXXXXXXxxXXXXXXXxXxXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$XXXXXXXXXXXXXXXxxxxx+x+++xx;;:::::::::::::::::;:::::::;;;;;;+++++xxxXXXXXXXX$$&&&&&&$XXXXXXXxXXXXXXXXXX$$&&&&&&&&&&&&&&&&&&&$$$$$$$$$$&$$$$$$X$$$$$$X$$$$$$$$$XXXXXXXXXXXX$XX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$&$$&&&&&&&&$$$$&$$$$;++++++xX
xxXXXXXXXXXXXxXXXXXXXXXXXXXXXXXXxXXxxxxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxXXXXXXXXXXxxxxxxxxxxxx++xxxxxxxxxxxxXXxxxxxXXXXXXXXXXXxXXxXXXxxxxx++++++++++x;:::::::::::;;::::;::::::::;:::::::::;;;xXxXXXXXX$$$$$$$&&$$&$XXXXXxxxxxxxXxxXXXXXX$&&&&&&&&&&&&&&&&&&&&&$$$&$&&&$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXx$X$XXXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$&&&$$$$$$$$$&&$&&&&&&&&&&&&&&&&&&&&&&&$$$$$&$$$
XxXXXXXXXXXXxXXXXXXXXXXXXXXXXXXXxXXxxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXX$XXXXxxxx+xXXXXXXxxxxxx+;:;++:...::::::::::;;;;;;+x++++++x++xxxxxxxx+x++++++++++;;:;;;:::::::::::;:;:::::::::::::::::;;;;;+++++xxxxx++++;;;+;;+;;;+xxxxxXxXxxXXXXxxxxx$X$&&&&&&&&&&&&&&&&&&&&&&&&&$$$$$&$$$$$$$$$$$$$$$$$$$$$XXXXXXXXXX$XXXXXXXXXXX$$X$$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$&$&$$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$&&&&$&$$
XxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxXXXXXXXXXXXXXXXXXXXXXXXXXX$$$$$$$XXx+x++xxXxxxxx+:....:............................:.......::;::;;;;::;:.::::::::::::::;;;;;;;;;:;;::::::::::::::;;;;;;+;++++++++;++xxxXXXxx::;;x;+x++x+;;;xx+++++x;xX&&&&&&&&&&&&x+xxxxxxxxxxxxxXX$$X$$$$$$$$$$$$$$$$XXXXXXXXXXxXXXXXXXXXXXXXXXXX$XXXXXXXXX$$$$$$$$$$$$$$$$$$$$$$&$&$&&&&&$&&&&&&&&&&&$&&&&&&&&&&&$&$&&&&&&&&&$&&&&$&$$$
xxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$XX$XxXXxx+xxxxx;:..........:::..................:.:::::::::::::::;::::;::::::::::;;;;;:;;;;;;;;;;::::::::;;::::::::::;;;;;;;;;;;xxxx$X$$$XXXXXXx++++xxxxX$X$&&$$$&&&&&&&&&&$$$Xxxxxxxxxx+xxxxxxxxxxxX$XX$$X$$$$$XX$X$$$XXXXX$XXXXXXXXXXX$$$$X$X$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$&&$&&&&&&&&&&&&&&&&&&&&&&&$&&&&&&&&&&&&&&&&&&&&&&&&&&$$$
xxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$XXXXxxxxx:..............:........::::::::::;:::::::::::::::xxxxx+xxxXxxxxxxxxxxxxx+++++++;;+;;;+;;:::::::::::::;;;;;;;;;;;;++++++;;+;;;;;;+++;+;;;;+++++++x$&&&&&&&&&&&Xxxxxxxxxxx++++++++x++++x$&&&&&&&&&&&&&&&&&&&&&$X$X$$$$X$$X$$$$$$$$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$&&&&&&&$&&&$&$$&&$$$$$&&&$&&&&&&&&&&$&&&&&&&&&&&&$
XxXXXXXXXXXXXXXXXXXXXXXXX$XXXXXXXXXxxxxxXXXXXXXXXXXXXXXXXXXXXXXXXX$XXXX$$$$$$XXXxx+........:.....::::::.::;::::::;;::;;;x+;;;;+x+:;+xxXXXXX$$$$$$&$$$X$X$$$$$$$XXXXXXXXXXXXXXX$Xx;;:.::;:;:;;;;;;;;;;;;;;;;;;;;;;;;:;::::;;:::;;;;;;++++;&&$$$$Xxxxxxxxxx++xx+++++++++++++X$X$$&&&&&&&&&&&&&&&&&&&&&&&&&&$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$&&&&$$$$$$$$&&&&&&$$$&&&&&&&&&&&&&&&&&$&$&&&$&&&&&$$
xxXXXXXXXXXXxXXXXXXXXXX$$XXXXXXXXXXxxxXXXXXXXXXXXXXXXXXXXXXXXXX$$XXXXXX$$$$$X$XXxx;................:::::;;;;;++++xxxxxxxxxxxxXXXXXXXXXX$$$$$XXXX$$$XXXXXXXXXXXX$X$$$$$$$$$$$$$$$$$$$X$$$$$$$$$$$$X$$$XXXXXXXxxx+;;;;:::::::;;;;;;;;;;;;;+++xxxxx+++xxxxx+++xx+++x++++++++xxxxxXX$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$$$$$$$$$$$$$$&&$&$$$$$$$$$$$$$$$$&$$$$$$$$&&$$&$&&&&&&&&&&&&&$&&&&&&&&&&&&&&&&&&&&&&&&$&&&&$$&
xxXXXXXXXXXXXXXXXXXXXXXXXX$XXXXXXXX+xxXXXXXXXXXXXXXXXXXXXXXX$XXXXXXxx+xxXX$XXXXXx;:.... .......:::::;;::+xxx++xxxxxxxxXX$$X$$$$$$XX$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$Xxx;;x++x+++++;+x++++++x+++++++++:xxxxx+++++x++++xx+x+xxxxxxxxxxX$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$&&$$&&&&$$&$$$$$$$$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$$$&&&&&&&
xxXXXXXXXXXXXXXXXXXXXX$XXXXXXXXXXXX+xxXXXXXXXXXXXXXXXXXXX$XXXXXXXXxx++++xxXXXXXx++:............::::+x++xxXXxx$$&&$$$&&&&$$$&$X$XXX$$$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxXXXXXXXXxXXX$$$$$$$$$$$$$$&$$$$$$$$$$$$Xxx+;+;;+++++++++++++;+;;+++++++++x+++++xxxxxx++++++++xxxxxxxxxxxxxxxXX&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$&&&&&&&&&&&$$&&$$&
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxXXXXXXXXXXXXXXXXXXXXXXXXXxx+++++;++xxXXXx+;...........:+;;xxxx+X$$$$$&$$&&&&&&&&$&&$$$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$$$$$$&&$$$$$$$&&$&&&$$&$$$$$$$$$$$$$X$Xxxxxxxx++:::;;;:;;;;++++++++++++x+xxxxx++xx+xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxXX&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$&&&&$&&&$&$$&$$&
XXXXXXXXXXXXXXXXX$XXXxXXXXXXXXXXXXXxxxxXXXXXXXXXXXXXXXXXXXX$XXXxxx+++;+;;;++xXXxx;..........::;+xxxxxX&&$&&&&&&&&$&&$&&$$$$$$XXXxXXXXX$XXXXXXX$XX$X$$$$$$$$$$&&&&&$&&$$$&$$$$$$$$$$XXXXXXXX+xxxx+x++;;::::::::::::;;;+;;;;+++++++++++xxxxxxxxxxxxxxxxxxxxxxxxxxXxxxxXXXXXXxxxxxxxxxxxxxXxxX$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$&&&&$&&&&$$$$$$$$&$$$$$$
xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxXXXXXXXXXXXXXXXXXXX$XXXxxx+++;;;:..::;++x++:..........::+;+++xxX&&&&&$$$$$$$$$XXXXXXXXXXXXXXXXXXXX$X$$$$$$$&&&$&&&&&&&$$$$$$$Xxxxxxxx+x++;++++++;;;::::;:::::::::::::;::;;;;+;+++++++++++xxxxx+xxxxxxxxxxxxxxxxxxxxxxxXXxXXXXXXXXXXXxxxxxxxxxxxxxxxxXXX$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$&&$$$&&&$&$$$$$$$$$$$
XXXXXXxXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxXXXXXXXXXXXXXXXXXXXXX$xxxxx++;:::...::;;+++;..... ....::;:+++xxxX$&x$$$$$XXXXXXXXXxxXxXXXXXX$$$$$$$$$$$$$$&&$$&$$$$XXXXXXXXxxx++;;;:::::.........::::::::::::::;;;;;;;++++++++++++xx+xxxxx+xxxxxxxxxxxxxxxxxxxxXxXXXXXXXXXXXXXXXXXXxxxxxxxxxxxxxxxxxXXXXXX$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$&&$$$&$&&&&&&$$$&$$$$$$$$$
XxXxxXXxXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxXXXXXXXXXXXXXXXXXX$XXxxxx+;+;;;:::.:::::+x+;...........::::::;;+xxxXxXxxxxxxxxxxxxxXxXXXX$$$$$$$&$&$&&&$&$$$XXXXXXXXx++++;:....:................::::::::;;;;;;;;+++++++++++++x+xxxxxxxxxxxxxxxxxxxxxxxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxxxxxxxxxxXXXxXXXXX$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$$$$$&$&$&$$$$$$$$$
XXxXXXXXXXXXxXXXXXXXXXXXXXXXXXXXXXXxxXXXxXXXXXXXXXXXXXXXXXxx++;;;;;;+::::..:::+++;..............::::::::;++xXxxxxXxxxxxxxxxXX$$$$$$&&&&$$$$$XXXXXXXXxx++:.......................::::::::;;;;+;+++++++++++++++++x+x++x+xxxxxxxxxxxxxxxxxxxxxxxxxxxxxXXxxxxxxXxxxxXxxxxxxxxxxxxxxxxxxxxxxxxxXXxXxXxxxxXXXX$$$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$$$$&&$&$$$$$$$$$$$$$$$&$$$$$$$$$$$$
XXXXXxXXXXXxXXXXXXXXXXXXXXXXXXXXXXXxxXXXxxXXXXXXXXXXXXXXXx+x++:;;+;;;;::.....:;+;;.....................::::::::+xxxxxxxxxXXX$$$$$$$$$$$XXXXXXXXXxx+;::.......................::::::;;;++++++++++++++++++++++++xxx+xxxx++xxxxxxxxxxxxxxxxxxxxxxxxXXxxxxxxxxxxxxxxxxxxxxxxxxXxxxxxxxxxxxxxxxXxXxXXXXxxxxXXXXXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X$XXXXX$$$$$X$$$$$$$$$$$$$$$&&$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
XXxXXXXXXXXXXXXX$XXXXXXXXXXXXXXXXX$xxxxxxxxXXXXXXXX$XXXxx+++++;:;;::;+;::...:::+;;...... .....................:::::::;+xxXX$$X$$$$XXxxxxxxx++;::::.....................:::::::;;;;+++++++++++++++++++++++++++x+x+xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxXxxXxxxxxxxxxxxxxxxxxxxxxxXxxxxxxxxxxxxxxxxxxxxXXXxxXXxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$&$$
XxXXXXXXXXXXXXXX$XXXXXXXXXXXXXXXXXXxxxxxxXXXXXXXXX$XXXxxxx+++;:;:;;;;x;;::....:;+;:....... ......................::::.:::+xxxXXxxxxxx++;::::::.......   ..........:::::::::;;;++++++++++++++++++x++++++++++++xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxXxxxxxxxxxxxxxxxxXXXXXXXXXXXXxXxXXXXXXXXXXXxXXXXXXXXXXXXXXXXXXXXX$XX$$X$$$$XXXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxXXXXXXXXXXXXxx++++++x::.:::+++;::...;+;++:::....................................:::::;;;:::::......................::::::::::;;;;;++;;;+++++++++++++++++++++++xx+xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxXXxxxxxxxxxxxxxxxxxxXXxxxxxxxxxxxxxXxXXXXXXXXXXxxxxxxXXXXXXxXXXXXXXXXXXXXXXXXXXXXXXX$$X$$$$$$$$$$$$$$$$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxXXXXXXXXXXXxxx++;++x+::.:.:;+++;::;.:+++++;::...................................................................::::::::::;;;+;;;;;++++++++++++++++++++++++xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxXXXXXXXXXXXXxXXXXXXXXxXXXxXXxXXxXxxxxxxXxxxxxxxxxxxxxxXXXXXXXXXXXXXXXxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$$$$$$$$$XXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
XXXXXXXXXXXXXXXXX$XXXXXXXXXXXXXXXX$xxxxxXXXXXXXXXXXxxxx+;:;xx;;:.:.;+++x+;;;;;;++++;:::.... ............................................................::::::::;;;;;;;;++++++++++++++++++++++++++++++++xxxxxxxxxxxxxxxxxxxxxxxxxxxxxXXXXxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxXXXxxxxxxxxxxxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$$$X$$$$$$$$$$$X$$$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
XXXXXXXXXXXXXXXX$$$$XXXXXXXXXXXXXX$xxxXXXXXXXXX$XXxxxx+;:::;+;:..::;+xxxx;;;;+++xx++;:::....... ......................................................::::::;:;;;;;+;;;;++++++++++++++++++++++++x+++++xx++xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxXxxxxxxxxxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$XX$X$$$$$$$$$$$$$$$$$$$$$$$$XXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X
xXXXXXXXXXXXXXXX$X$$XXXXXXXXXXXXXX$xxXXXXXXXXXXXXXxx++;;:..:..:...:++xxxx+;;;;;x+xx++;::........ ...................................................:::::::;;;;;;;;;;;++++++++++++++++++++++++++++++++xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxXxxxxxXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxxxXxXXXXXXXXXXXX$X$XXXXXXXXXXX$XXXXX$XXX$$XXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
XxXXXXXXXXXXXXXXXX$$$XXXXXXXXXXXXXXxxXXXXXXXXX$XXxx++;;:...::....:++xxXxxxx+;;;+xxxxx;;:::..... ...................................................:::::::::;;;;;;++++++++++++++++++++++++++++++++++xxxx+xxxxx+xxxxxxxxxxxxxXXXXXXXXXXXXXXX$XXXXXXXxXXXXXxxxxxxXxXXXXXXXXx:+xXXXXxxxxxxXxXXXXXXXXXXX$$$$$$X$$XXXXXXXXXXX$$XXX$$$$$$$$$$$$$$$$$$$$$$$$$XXXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
XXXXXXXXXXXXXXXX$X$$$$XXXXXXXXXXXXXxxXXXXXXXXXXXxxx+;::....::..:;;+xxxxxxxxx++;+xxxxxxxx;:;:......................................................:::::::;;;;;++++++++++++++++++++++++++++++++++++++x+xxxxxxxxxxxxxxXXxXXXXXXX$$$$$$$&&&&&&&&&&&&$&$&$&$&&&&$$$$XXxxXXXxxx;;;+++xxx+xxXXXXXXXXXXXXX$$$$$$$$$$$$$$$XXXXXXXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
XXXXXXXXXXXXXXXXX$$$$$XXXXXXXXXXXXXxXXXXXXXXXXXxx++;:::....::..:++xxXxXxxxxx+;;;+xxxxxxxxx;;;:......................................... ........:::::::;;;;;;;++++++++++++++++++++++++++++++++++++++++++++xxxxxxxXXXXXXXX$$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$$$$XXXXx;;;;;;+xxxxxxxx+xxxxXX$$X$$$$$$$$$$$$$$$$XX$XX$$$$$$$$$$$$$$$$$$$$$$$$$$$$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X
XXXXXXXXXX$XXXXXXXX$$$XXXXXXXXXXXXXxXXXXXXXXX$Xxx+;;::.......;:++xxxxXxxXxxXxx;;++xxxXxxxxx+;;;;:..............::::......:.....................::::::;;;;;;;;++++++++++++++;;;;;;;;;++++++++++++++++++++++xxxxXXXXXX$$$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$$+xxXXXXXXXXXXXx++xxxxxx;;++x;+$$XXXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
XXXXXXXXXX$XXXXXXXX$X$XXX$XXXXXXXXXxxXXXXXXXXXxx++;::.....:.::;+xxxXXXXXXXXXXx;++++xxX$XXXX+xx;+;:. ......:.::;++;::.........................:::;:::;;;;++++++++++++++++;;;;::;;;;;;;++++++++++++++++++++++xxXXXXXX$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&xXXXXXXXXXXXXXXXXXXXXxxx++++x;;;+;;+;+$XX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
XXXXXXXXXXXXXXXXXX$$X$XXX$XXXXXXXXXxxXXXXXX$$xxx;;;:......:::;+xxxXXXXXXXXXXXxx+++++xxx$$$XXXX++++;;:......:;+++xxx;::::...................::::::::;;++++xxxxxxx+++++++;;;;:::::;;;;;+++++++++++++++++++++xXXXXX$$&&&&&&&&$&&&&&$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&+xxxXXXXXxXXXXXXXXXXXxXXXXXXXXXxxx++xxxx+++++;:x$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X
XXXXXXXXXXXXXXXXXXX$$$XXX$$XXXXXXX$xxXXXXXXXxx++;;:......:;;:+xxxxXXXX$XXXXXXXXx++;;+xxx$$$$$$XX+x++;::....:;++xxxxxx+::..............:...:.::::;;++++xxxXxxxxxxxxxx+++++;;::::::;:;;+++++++++++++++++++++xXXXX$$&&&&&&&&&&&$&$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&:;;:;;;+;+xxxxXxxXxxxXxXXXXXXXXXXXXXXXXXxxxxx+x+;;;;xxxX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
XXXXXXXXXXXXXXXXXXX$$$XXX$$XXXXXXXXxxxXXX$XXx++;;;::....:;;;xxxxxXXXXX$$$$XXXXXX++;;+xxxX$$$$$$XXx++++;:.....;+xXXXXXX++;................:::::;+;+;+xxxxxxxxXxxXXXXxxxx+++;;;::::::;;;+++++++++++++++++++xxXXXX$$&&&&$&&&&$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&xXxXXxx++;;:;;+++++x+xxXxxxxXXXXXXXXXXXXXXXXXXXxxxxxx+++++Xxx+x$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
XXXXXXXXXXXXXXX$XXX$$$$$$$$XXXXXXXXxxXXXXXXXx++;;::.....:;;xxxxxxXXXX$$$$$$$$XXXx;+;;+xxxX$$$&&$$XXx+x++:.....;+xXXXXxxx+;:........:....::::;;++++xxxxXXX$$$&&&&&&XXXxxxx++;;:::::::;;;+++++++++++++++++xxxXXXX$&&&&&&&&&&&&&&&&&&&&&&&&&&$&$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&XXXXXXXXxxxXxxxxxxxxx+;+xxxxxxxxxxxxxxxxxxxxx+xXxxXXX$XXXXXXxXxx+++xxxxXXx+x$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
XXXXXXXXXXXXXXXXXXX$$$X$$$$XXXXXXXxxxXXXXXXx+++;;::.....::;+x+xxXXXX$$$$&&$$$$XXXx;+++xxxX$$&&&&$$XXx+++;:.....;xxXXXxxxxx;;:.........:;:;;++++;XxxXXx$$&&&&&&&&&&&&$xXXXx+++;:::::::;:;++++++++++++++++xxXxXXX$$&&&&&&&&$$$$$$&$&&$$$$$$$$$$X$$$$$$$$$$$&&&&&&&&&&&&&&&&&XXXXXXXXXXXXXXXXXxxxxxxxxxxxxXXXxx+++xxxxxxXxxxXXXXXXxXXxXXXXXXXxXXXxx+xXx$XXXxXxx+;X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
XXXXXXXXXXXXXXX$XXX$$$$X$$$XXXXXXXXxXXXXXXX++;+;:......::;;++x+xxXX$$$&&$&&$$$$XXXxx+x+xxx$$$&&&&&$$Xxx+;;;.....;xxXXXXXxxxxx+++:;;:;;;;;+++xxXxXX$$$&&&&&&&&&&&&&&&&&$$XXxxxx+;::::;;;;;+++++++++++++++++xXXXX$&&&&&&&&&&&&$$$$$$$$$$$$$$$$$$$$$XXXXXX$$$$$$$$&&&&&&&&&&&xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxXXxxxxxx+x++xxxxxxxxxXXXXXXXXXXXXXXXXXXXXXXXxxxxXXXXXXXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
XXXXXXXXXXXXXXXXXXXX$$$$$$$XXXXXXXxXXXXXXxx++;;;:......:;++++xxxXXX$$&&$$$&&&$$$XXXXx+xxXXX$&&&&&&$$$Xxx++:.....;xxxXXXXXXXXxxxxx;++;++xxxxXXXX$$$$&&&&&&&&&&&&&&&&&&&&&$$XXxxx++;;::;;;;++++++++++++++++xxxxxXX&&&&&&&&&&&&&&&&&&&&&&&&&&&$&&$$$$$$$$$$XXXXX$$$$$$$&&&&&&xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxxxx+xxxxxXxxxxXXXXXXXXXXXXXXXXXXXXXXXX$XXXXXX$XXXXX$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
XXXXXXXXXXXXXXXXXXXX$$X$$$$X$XXXX$xxxXXXXx++;+;;.......::++++xxXXXX$$&&&&$&&&&$$XXXXXx+xXXx$$&&&&&&&$XXxx+:......xxxxXXXXXXXXXXxxxxxxxxxXX$$$$$&&&&&&&&&&&&&&&&&&&&&&&&&&$$$XXxxx+;;::;;;++++++++++++++++xxxxXxX$&&&&&&&&&&&&$$&&&&&&&&&&&&&&&&&&&&&&$$$$$$$$XXX$$$$$$&&&&xXXXXXXXXXXXXXxxXxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxxXxxxxxxxxxxxxxXXXXXXXXXXXXXxXXxXXXXXXXXXXXXXXXXXXXX$$$$$$$$$$$$$$$$$$$$$$$$$$$
XXXXXXXXXXXXXXXX$XXX$$$$$$$X$$X$XXxxxXXXxx++;;;;:...::::++++xxxxXXX$$&&&&$$&&&&&$$XXXxxxxXXX$$&&&&&&$$XXx+.......+xxxXXXXXXX$$$XXxxxxXX$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$$XXxxx+;::;;+++++++++++++++++xxxxXx$$&&&&&&&&&&$X$$$$$$&&&&&&&&&&&&&&&&&&&&&&&$$$$$$$$$X$$&&&XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxXXXXXxx;;;+++xxxXXXXXxxxxxXXXXXXXXXXXXXXXXXXXXXXXX$$$$$$XXXXX$X&&&&$$$
XXXXXXXXXXXXXXXX$XXX$$$$$$$$$XXX$XxxXXXxx+x;;;;;....:;:;+;;x++xxXXX$$&&&&&$&&&&&&$$XXXxXxXXX$$&&&&&&&$XXXx:......++xxxXXXX$$$$$$$$X$&$$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$X$xxx+;;:;;+++++++++++++++++xxxXX$$&&&&&&&&&$&$$$$$X$$&&&$&$$&&&&&&&&&&&&&&&&&&$$$$$$$$$$$$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX;;;;;+++++++;+++xXXXXXXXxXXXXXXXXXXXXXXX$$$$$$$$XX$&&&$$$
XXXXXXXXXXXXXXXXXXXX$$$$$$$XXXXX$$xXXXxxx++;;+;;:::::;:;;;;+++xxXXXX$&&&&&&&&&$&&&&$XXXXXXXX$$&&&&&&&&$$XX+.......++xxXXXX$$$$$$$$$$&$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$$$X$xxx+;;;+++++++++++++++++xxxxXx$&&&&&&&&&&$$$$XX$$X$$$$$$$&&&$$$$$&&&&&&&&&&&&&&&$$$$$$$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$x$$::::.::::++++xxx$$XXXXXXXXX$XXXXXX$&$&&&&&&&&&&$$
XXXXXXXXXXXXXXXX$XXX$$X$$$$$$X$XX$XXXXxx++;++;;:::::::::::;++xxxxXXX$$&&&&&&&&$&&&&&&XXXXXXX$&$&&&&&&&&$$xX;.......;++xXX$X$$$$$$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$&$$Xxx++;;++++++++++++++++xxxxXX$&&&&&&&&&&&&&$$XXXXXXXX$$$$$$&&$$$$&&&&&&&&&&&&&&&&&$$&&xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$&$$$$$$$$$x$&$+++xxx+++;+;;;;+x+x+X$$$$$$$$$&&&&&&&&&$$
XXXXXXXXXXXX$XX$$XX$$$X$$$$$$$$$$$xXXxxx++;++;;.;;;::;:::;;;+xxxxXXX$$$&&&&&$&$&&&&&&&$XXXXX$&&&&&&&&&&&&$Xx;:......;++xX$$$$$$$$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$$xxx;;;+++++++++++++++++xxXXx$$&&&&&&&&&&&&$$$X$XXXXXX$$X$$$$$$$&&&&&&&&&&&&&&&&&&$$&xxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$X$$X$$&&&$&&&&&&&$$&$$$&&$$$$$$$&&&&&&&&$$$$$$$$$$$&$&$$$$$$$$$XxXXX+:;:.::;+;;:;&$XX$&$$$X&
XXXXXXXXXXXX$XXXXX$XXXXX$$$$$$$$$$Xxxx++;;++;;:.;;;;+;;;;;;;+xxxxxXX$$$&&&&&&&&$&&&&&&&&&$$&&&&&&&&&&&&&$$$Xx+;:.....;+xX$$$$$$$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$$xxx+;;+++++++++++++++xx+XXXX$$&&&&&&&&&&&&$$$$XXXXXXXXXXXX$$$$$$&&&&&&&&&&&$$$$$$$$$XXXXXXXXXXXXXXXXXXXXXXXX$$X$&&&&&X$$&$$$$$$$$$&&&&&&$$$$$$$$$&&&&&&&$$$$$$&&&&&&&$$$$$$$$$$$$$$&$$$$$$$$$$$$$$$$$$$$XXXXx+;;::::::;;&
XXXXXXXXXXXXX$XXX$XXX$$$$$$$$XXX$$+xxx+;++++;;;:+;;;;;;;;;;;+xxxxXXXX$$&&&&&&&&$&&&&&&&&&&&&&&&&&&&&&&&&$$$$Xx+;:.....;+xxXX$$$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$Xxx+;;+++++++++++++++x+xxXXx$&&&&&&&&&&&&&$$$XXXxxXXXXXXXXXXX$$$&&$&&&&&&$$$$$$$$$$$$$XXXXXXXXXXXXXX$X$$$$&$$&&&$$$$$$$$$$$$$$$$$&&&&&$$$$$$$$$$$$&&&&&&$$$$&&&&&&$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XxxxXxXx:;$
XXXXXXXXXXXXXXXXX$XXXXX$$$$$$$$$$X$++;;++++;;;+++;;;;;;+;;;;+x+xxXXXX$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$$$XXx++::....;xXXX$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$XXx++;+++++++++++++++x+xxXXX$&&&&&&&&&&&&&$$$$$XXxxXXXXXXXXXXXXX$&&&&&&&&&$$$$$$$$$$$$$X$$$&&&&$$$$$$$$$$$$$$$$$$$$X$$$X$$$$$$$$$&&&&&$$$$$$$X$$$&&$$&&&&&&&&$$$$$$$$$$$$$$$$$$$$$$$$$$$&$$&&&&&$$&$$$$$$$$$$$X$$$$$X+$
XXXXXXXXXXXXX$XXXXXXXXX$$$$$XX$$$Xx++;;;+++;;;++;;;;++;+;;;;;+++xxXXXX$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$$$Xxx;::....+xXX$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$$Xx++;++++++++++++++++++xXXX$&&&&&&&&&&&&&$$$$$$XXXXXXXXXXXXXXXXX&&&&&&&&&$&&&$$&X$$$$$&&&&&&$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$&$$&&&&&&$$$$X$$$$$$$$$$$$$$&&&&$$$$$$$$$$$$$$$$$$$$$$$$$$&&&&&&&&&&&&&$$$&$$$$$$$$$$$X$
XXXXXXXXXXXX$$X$$XXXXXXX$$$$$$$$$X+++++;;+++;;++;;;;+++++;;;;+++xxXXXX$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$$$$Xxx;:....:;XXX$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&XXxxx+++++++++++++++++++xxX$$&&&&&&&&&&&&&$$$$$XXXXXXxXXXXXXXXXXXX$&&&&&&&&&&&&$$$$$$$$$&&&&&$$$$$$$$$$$$$$$$$$$$$$$$$$$$$&&&&&&&&&&&&$$$$$$$$$$$&&&&&&&&&&&&&&&&&&&&$$$$$$$$$$$$&&$$&&&&$&&&$&&&&&&&&&&$$$$$$$$$$$$$
XXXXXXXXXXXX$$$$$$$XX$$$$$$$$$$XXX:;++++;;++++++++++++++++;;;+++xxXXXX$$&&$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$$$$XXx;::...;+XX$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&XXxx+++++++++++++++++++xxXX&&&&&&&&&&&&&&$$$$$$XXXXxXXXxXXXXXXXX$X&X$&&&&&&&&$$$$$&&$$$$$$&$&&&&$$$$$$$$$$$&$$$$$$$$$$$$&&&&&&&$&&&$&$$$$$$&&&&&&&&&&&&&$&&&&&&&&&&&&&&&$$&$$&&$&&&&&$&&$$&&$&$$$&&$&$&$&&&&&&&$$$$
XXXXXXXXX$X$$$$$$$$X$$$$$$$$$$$$XX:;++++++++++++++++++++++++;;+++xXXXX$$&&&&&&&$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$$$XX+;:....;+XX$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&XXxx++++++++++++++++++xxxx$&&&&&&&&&&&&&&$$$$$$$XxXXXXxxXXXXXXXXX&&&&&&&&&&$$$&$$$&&$$$$&$$$&&$&$$$$$$$$$$$$&&&&$$$&$$$$$$&&&$$$$&$$$$$$$$$$$$$$$$$$$$$$$$&$&$&$&&&&$$$$$&&&&&&&&&&&&&&&&&&&&&$$&$&$$$$&&$$&&&$$&
XXXXXXXXXX$$$$X$$$$X$$X$$$$$$$$$XX:;++++;+++++++++++++++++++;;+++xxXXX$$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$$XXX+::....;+XX$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&XXXxx+++x+++++++++++++++XXX$&&&&&&&&&&&&&$$$$$$X$XXxXXxxxXXXXXXXXX&$&&&&&&&$$$$$$$$$$$$$$$&&&&&&$$$$$$$$$$$$$$$$$$X$$$$&&&&&&&&$$$$$$&$$$$$$&$&&&&$&$$&$$$$$$$$$$$$$$$$$$$$&$$$&$$$$$X$$$$$$$$$&&$$$$&$$$$$$$$$$&
XXXXXXXXXXX$$$X$$$$$$$$$$$$$$X$$XX:;+;+++++x+++++++++++++++++++++xXXXXX$$&&&&&$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$$XXX+::....+xX$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&XXXXxx++++++++++++++++++xXx$&&&&&&&&&&&&&&&$$$$$$$XXXXXXxxXXXXXXXXX&&&&&&&$$$$$$$$$X$X$$$$$$$$$$$$$&$&&&&&&&&$&&&$&&&&&&&&&&&&&&&&&&&&&&&&$&&&&$&&&&&&&&&&&$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XX$$$$$$$$$$$$$$X$$&
XXXXXXXXXX$X$XX$$$$$$$$$$$$$$$X$$$;:;;;;+xXxx+++++++++++++++++++xxxxxxX$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$$$XXX+::....+xX$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$XXXxx+x+++++++++++++x+xxXXX$&&&&&&&&&&&&&&$$$$$$$XXXxXXxxXXXXXX$XX&&&&&&$$$$$$$$$$$$$$$$$$$&$&$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$&&&$&&&&$$$$$$$$$$$&$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XX$$
XXXXXXXXXXX$$$X$$XX$$$$$X$$$$$$XXX+.:.;++xxXxx+++++++++++++x++++++xxxXX$$&&&&&$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$$XXX+::...:xXX$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&XXXXxx+x++++++++++++++++x+xXXX&$&&&&&&&&&&&&$$$$$$$XXXxXxxxXXX$XX$$$$&&&&$$XXX$XXXXXXXXXX$$$$$$$&&&&&&&&&&&&&&&$&&&&&&&&&&&&&&&&&&&&&&&&&&&$&&&&$$&$&&&&&&&&&&$$&&&&$$&&&&$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
XXXXXXXX$$$$$$$$$$$$$$$$X$$$$$$XXX:....;;xXXXxx+++++++xx+++xx+x++xxxxXX$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$$XXX+::..:;xX$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$XXXxxxx+++++++++++++++++++x+xXX$$$&&&&&&&&&&&&$$$$$$$$XXXxxxXXXXXX$$$$&&&XXXXXXXXXXXXXxXXXXX$$$$$$$$$$$$&&&&&&&&&&&$&&&&&$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$$&&&$&$$$$$$$$$$$$&$&$$$$$$$$$$$$$$$$$$$$$&
XXXXXXXXX$$$$$$$$$$$$$$X$X$$$XXXXx:....;+xXXXXxx+++++xxx+xxx+xxx+xxxxXX$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$XXX++::...;xX$&&&&&&&$$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$XXXxxxx++++++++++++++++++++xxxXX$$$&&&&&&&&&&&&$$$$$$$$XXXXxxxxXXXX$$$$&&XXXXXXXXxxXXxxXxXXXxxXXXX$X$$$$$$$$&&&&&&&$&&&&&&&&&&&&&&&&&&&&&&&&&&&&$$&&&&&&&$&&&&&&&&&&$$$$$$$$$$$$$$$$$&&&&$$$$&$$$$&$$$$$$X$$$$$
XXXXXXXX$$$$$$$$$$$$$$XX$$$$XXXxxx::.::;+xXX$Xxx++++++xxxxxxx+xx+xxxXX$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$XXX+;::.:;xXX$&&&&$XXXXX$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$$XXxxxxx++++++++++++++++++++++xxXXXX$$&&&&&&&&&&&&&&$$$$$$XXXxXXXxxXXXX$$$$$X$$$XXXXXXXXXXXxXxXXXXXxXXXXXXXXXX$$$$&&$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$$&$$&&&&&&$$$$$&$&&$$$$$$$$$$$$
XXXXXXXX$X$$$$$$$$$X$XX$XX$XXXXxx+;:::;;+xX$$$Xxx++++++xxxxxxxxxxxxXXX$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&XXXXx:::..+xXX$&&&$XXXXXXX$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$XXxxxxx+++++++xx+x++++++++++++x+xxxXX$$&&&&&&&&&&&&&&&$$$$$$$XXXXXXXXXX$$$X$$$$$$$$$X$$&$XXXXXXXXXXXXXXXXxxxXXXXXX$$$$$$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$&&&&&&&$$$$$&$&&&&&&$$$$$$$$
XXXXXXXXXX$$$$$$X$XXXXXX$XXXXXxx+x;:::;+xxX$$$$Xxx++x+++xxxxxxxxxXxX$$&&&&&&&&&$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&XXXX;::.::+xX$$&&&$XXXXXXXXX$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$XXXx+++++++++++xx+x+++++++++++x+xxxxxxXX$$&&&&&&&&&&&&&&&$$$$$$XXXXXXXXXXXX$XX$$$$$$$$$$$$$$$$$$$XXXXXxXXXxxxxxxxxxxXXX$XXX$$$$$$$$&$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$$$$$&&&&&&$&&$$$$$$$
XXXXXXXXX$$$$$$$XXXXXXXXXXxXxxxx+;+:.;;+xxXX$$$XXx+++++xxxxxxxxxxXXX$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&XXXX;.::::xxX$$&&$$XXXXXXXXX$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$$$XXxx++++++++++xxxx++x++++++++++xx+x+xxxxXXX$&&&&&&&&&&&&&&&$$$$$$XXXXXXXXXX$XX$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXXxXXXXXxxxXXxXXX$$$X$$$$&$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$&&&&&&&&&&&&&&$$&
XXXXXXXXX$$$$$$$XXXXXXXXXxXXXxxx++;;;;++xxXX$$$$XXx+++++xxxxxxxXXXX&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$XXXx:.:::+XX$$&&&$$XxXXXXXXXX$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$XXXxx+++++++++++xxx+++++xx+++++x+x+xxxx+xxxxXXX$$&&&&&&&&&&&&&$$$$$$XXXXXXXXX&$$X$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXxXxXXXXXXXXxXXXXXXXXXXXXX$$$$$$$$$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$$
XXXXXxX$$$$$XX$XXXXXXXXXxxXXXxxx+++;+++xxxX$$$$$$XXXx+x+++xxxxXXX$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&XXXXx..:::xxX$$&&&&XXXXXXXXXXX$$$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$XXXXxx++++++++x++x++xx+++++++++x+x+xxxxxxx+++xxxxXXX$$&&&&&&&&&&&&$$$$$$$$XXXXX$$$$XX$$$$$$$$$$$$$$$$$$$$$$$$&&&&&&XXXXXXXXXXXXxXXXXXXXXXXXXXXX$$$$$XX$X$$$$$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$&&&&&&&&&&&&&&&&&&$$
XX$XXXXX$$$XXX$XXXXXXXXxxxxxxxxxx+++++++xxX$$$$$$$$XXXXxxxxXXX$$$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&XXXX.::::;xX$$$&&&&$XXXXXXxXXXX$$$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&$$XXXXxx++;++++++++xxxx+xx+++x+x+++xx+x+xx++x+xxxxxxxXXX$$$&&&&&&&&&&&&$$$$$$XXXX$$$$$XXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXXXXXXXXXXXXXXXXxXXXXXXX$$$$$$$$&&&$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$
XXXX$$XX$$XXXXXXXXXXXXxxxxxxxxxx+++++++xxx$$&&&&$$$XXXXXXx$XX$$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&XXXX:::::+xX$$&&&&&&XXXXxxxXXXXXXX$&&&&&&&&&&&&&&&&&&&&&&&&&&$$XXXXx++++++++++++xxxxxx++++++x+x+xx+xx+++++++x+xxxxxxxxX$$$$$$&&&&&&&&&&&$$$$$$X$$$$XXXXX$$$$$$$$$$$$$$$$$$$$$$$$&$$$$$$$$$$$$$X$$$$$$XXXXXXXXXXXXXXxXXXXXXXXXXXXX$X$$XX$$$$&$$$$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$
XXXX$XXX$$XXXXXXXXXXxxxxxxxxxx+++++++++xxx$$&&&&$$$$$$$$$XXX$$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&XXXX::::;xxX$$&&&&&&&$XxXxxxXXXXXX$$&&&&&&&&&&&&&&&&&&&&&&$$X$XXXxxx++++++++++xxxxx+xx+++++xx+++++xxx+x+x+x++x+xxxxxxxxxXX$$$$$&&&&&&&&&&&$$$$$$$$XXXXXXX$$$$X$$$XX$$$$XX$$$$$$$X$$$$$$$$$$$$$$$$$$$$$$$$XXX$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$XX$$X$$$$$&&&&&&&&&&&&&&&&&&&&&&&&&$$$&
XXXX$XXX$X$XXXXXXXXXxxxxx+xxxxx++++++++xxX$$&&&&$$$$$$$$$X$$$&&&&&&&&&&&&&&&&&&&&&&&&&&&X&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$XXX+;:::+xX$$$&&&&&&&$XxxxXxxXXXXXX$&&&&&&&&&&&&&&&&&&&&$$$XXXxXx+;+++++++++++xxx+++xx++++x++++++xxxx+xx++++++xxxxxxxxxxxx$$$$$$&&&&&&&&&&&$$x$$$XXXXXXXXXX$XXXXXXXXXXXXX$$$$$XXX$$$$$$$$$$$$$$$$$$$$$$$$$$$XXX$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$X$$$$$$$$$$&&&&&&&&&&&&&&&&&$$$
XXXXXXXXXX$XXXXXXXxxxxxxx++++x++++++++xxXX$$&&&&&&$$$$$$$$&$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$XXX;:::;+xx$$$&&&&&&&&$XxxxxXxXXXXXX&&&&&&&&&&&&&&&&&&$$$XXXXxxx+++++++++++xxx+x++xx+xxx++x+x+xxx++xx+++++x++++xxxxxxxxxxxxX$X$$$&$&&&&&&&&&xxxXXXXxxXXXXXXXXXXXXXXXXXXXXX$XXXXXX$$$X$XX$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$X$$$$$$$$$$$&&&&&&&&&&&$X$
XXXXXXXXX$XXXXXXXXxxxxxx++++++++++++++xXXX$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$XXx;:::+xx$$$&&&&&&&&&$XXxxxxXXXXXX$&&&&&&&&&&&&&&&&&$$X$XXxxx++++++++++++xxx+++x+xxx+xxxxxx+x+++xxx++xxxxxx++++xxxxxxxxxxxxxXX$$$&&$&&&&&&xxxxxxxxxxXXxxXXXXXXXXXXXXXXXXXXXXXXXXXXXX$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$X$$$$$$$$$$$$$$&$$$$X$
XXXXXXXXX$XXXXXXXxxxx+++++++++++++++xxXXXX$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$XXX;::;;+xX$$$&&&&&&&&&&$XXxxXxXXXXX$&&&&&&&&&&&&&&&$$$XXXxx++;++++++++++x++x+x+xxx++xx+x+xxxxxx+++++++xxxxxx+++++xxxxxxxxxxxxxxXX$$$$&&&&&XXxxxxxxxxxxxxxxXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXX$XX$XXXXXXXXXXXXXXXXXXX$XXXXXXXXXXX$$$$$$$$$$$$$$$$
XXXXXXXXXXXXXXxXxxxx++++++++;;;;+++xxxXXX$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&XXXX:::;;xxx$$$&&&&&&&&&&&$XxXXxXXXXX$$&&&&&&&&&&&&&$XXXXxXx++++++++++++++++++xx++++xxxxx+x+xxxx+xx++x++++xxxxxx++++++xxxxxxxxxxxxxXX$$$$&&XXXXxxxxxxXxxxxxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$XXXX$$$$$$$$$X$XX$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXXXXXXXXXXXXXXXXX$$$$$$$$
XXXXXXXXxxxXXX+xxx;;++++;++;;;;;;+xxxxxX$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&XXXX;:::;+xxX$$&&&&&&&&&&&&&XXXXxXXXXXX$&&&&&&&&&&&$$XXXXXxx+;;++++++++++++xxxx+++x+xxxxxxx++xxx+x+x++x+++++++xxxxx+++++xxxxxxxxxxxxxxXX$$$xxXXXXXxxxxxxxxxxxxxXXXXXXXXxXXXXXXXxXxXXXXXXXXXXXXXXXXX$$$XX$X$$$$$$$$$XXXXXX$XX$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXX$XXXXXXX$$$XX$$$$$$X$
XXXXXxxxxxxxxxxxx+;;;;;;;;;;;;;;++xxxxXX$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$XXXx::::;+xx$$&&&&&&&&&&&&&&&&XXXXXX$XX$&&&&&&&&&&$$XXxXxxx+;+;+;+++++++++x+x+++xxxxxxxxxxx++xxxx+x+x++xxxx+++++xxx+++x+++x+xxxxxxxxxxxxxXxxxxxXxXxxxxxXxxx++xxxxXXXXXXXXXXXxXXXxxXxXXxXXXXXXXXXX$XXXX$X$$$X$$$$$XXX$$XXXXXX$X$$$$$$$$$$$$$$$$$$$$$XXX$$$$$$$$$$$$$$$$$$$$$$$$$$
XXXXXxx+xxxxxxxx;;;;;;;;;;;;;;;+++xxXXXX$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$XXXX::::;;xxX$$&&&&&&&&&&&&&&&&&X$X$XX$&&&&&&&&&&&$$XXXxxx+++++++;+++++++x+xxx++xxxxxxxxxxxxx+xxx+++++++xxxx+xx+x+xxxxxxxx+xxxxxxxxxxxxxxxXxxxxxxxxxxxx+xxxXXxxxxxxxXXXXXxxxxxxxxXxXXxXXXXXXXXXXXXXXXXXX$$X$$$X$XXXXXXXXX$$X$XX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
XXXXXxx+x+xxxx+;;;;;;;;;;;;;+++++xxXXX$X$$&&$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$XXXx::::;;xxX$$&&&&&&&&&&&&&&&&&&$$$&&&&&&&&&&&&$$$XXxxx+++++++++++++++++xxx++++xxxxxxxxxxxxxx+x+x++++xx+x++++xx++XxXxxxxxxxxxxxxxxxxxxxxXxxxxxxxxxxxxxxx+xxXxxxxxxxxXXXXxxxxxxxxXxxXxxxXXXXXXXXxXXXXXXXX$XXXXXXXXXXXXXX$$$X$$$$$$$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
XXXXXXXxx+xxx++;;;;;;;;;;;;;+++++xxxXX$$$$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$XXXx:::::;;xxX$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$$XXxxx+++;++++++++++++++xxxxx++xx+xxxxxxxxxxx+x++++++++x+x++xxx++xxxxxxxxxxxxxXxxxxxxxxxXxxxxxxxxx+xxxxxxxxxXXxxxxXXxXXxxxxxxxxxXXXXxxxxXxXXxXXxxXxXXXXX$$XXXXXXXXXXXXXXXXX$$$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X
XXXXXxXXxxxxx++;;;;;;;;;;;;;;++++++xX$$$$$$&&$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$XXX+::::::;xxXX$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$$$XXxxx++;+;++++++++++++++xxxx++xxx+xx+xxxxxxxxxx++++++xxxxx+xxxxx+xxxxxxxXxxxxxxxxxxxxxxXXXXxxxxxxxxxx+xxxXXXxxXxxxXxxxXXxxxxxxxxXXXxXXxXXXXXXXXxxxxxXXX$X$XXXXXXXXXXXXXXX$$$XXXXX$X$$$XXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
XXXXXXXxx+x++++;;;;;;;;;;;;;;+++++++X$$$$$$$&&&&&$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$XXXx;:.::::;xxXXX&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$$XXXxx+;;+;+++++++++++++++xx++++x++x+xxxxxxxxxxx+++++++++++x++xxxx+xx+xxxxxXXxxXxXXxXxxxxXxXXXXXxxxxxxxxxXxxXXXXXXXxxxxxxxxxxxxxxxxXXxxxxxXXXXXXXxxXXxXXXX$XXXXXXXXXXXXXXXXXX$XXXXXX$XXXXXX$$$$$$$$$$$$$$$$$$X$XX$XX$$$$$$$$$$$
XXXXXxxx++x+++++;;;;;;;;;;;;;;;;++++$$$$$XX$$$$$&$$&&&&&&&$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$XXXx;:.::::;+xxXXX&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$$XXXx+++;++++++++++++++++++x+++++xxx+++x+xxxxxxxxxx+x++++++++x+++X+x+x+xxxxxXXXXxxxXXxxxxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxxxxxxxxXXxxxxXXXXXXXXXXXxXX$$XXXXXXXxxXXXXXXXXXX$$XXX$$$XXXXX$$$$$$$$$$$$$$$XXX$XXXXXXX$$$$$$XXXX
XXXxxxx++x+++++;;;;;;;;;;;;;;;;;;;+++$X$$XXX$$$$$$$$$&&&&&$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$X$Xx;::::::::+xXXXX&&&&&&&&&&&&&&&&&&&&&&&&&&&&$$XXx+;;:;;+;++++++++++x+++++x++++xxxxx+++x+xxxxxxxxx++x++++++++xXXxxXx++xxxx+xxXXXXXXxxxxxxxxxX$$$$$$$&$$$&&$XXXXXXXXXXXxxxxxXxxxxxxxxxxxxxxxXXXXXXXXxXXXXXXXXXXXXxxXxXXxXXX$$$$$$$$$$$XX$XX$$$$$$$$$$$$XXXXXXXXXXXXXXXXXXXXXXX
Xx++++++xx+++++;;::::::;::;;;;;;;;;++xX$$$X$$$$$$$$$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&X$Xx+::::::::;+xXXXX$$&&&&&&&&&&&&&&&&&&&&&&&&$$$XX++++;;;;;;+++++++++++++++x+xx++x++xx+xxx+xxxxxxxx+x+xx+++++++xxXXXXxxxxxxxxxxxxxXXXXXXxxxxxxxxx$$$$X$$$XX$X&XXXXXXXXXxxxxxxxxxxxxxxxxxxxxxxXXxXXXXXXXXXXXXXXXxXXxXxxXXXXXXX$$X$$$$$$X$$$XX$$$$$$$$$$XXXXXXXXXXXX$XXXXXXXXXXX
++++++++++++++;;;::::::;::;:;;;;;;;+++XXX+XX$$$$$$$$$$$&&&$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&XXXx;:::::::::;xxxxxx$$&&&&&&&&&&&&&&&&&&&&&&&&$$XX++++;+;;;;+++++++++++xx+x+++xx+++xxx+xxxxxxxxxxxxxxxxxxx+++++++xxXXXXXxxxxxxxxxxxxxXXXxxxxxxxxxxxxXX$$$$$&&&&&$XXXXXXXXxxxxxxxxxxxxxxxxxxxxxxxxxxXXXXXXXXxxXxxxxXxxxxXXXXXXXXXXX$$$$XXXXX$$$X$$$$$$XXXXXXXXXXXXXXXXXXXXXXXXX
++++xxx+++++;;;;:::::::::;;;;;;;;+;+xxx+++xXXX$$XX$$$$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&X$$x;:::::::.::;xxxxxx$$$&&&&&&&&&&&&&&&&&&&&&$&$Xxx+++++;;+;;;;++++++++++++++x+++++xxxxxxxxxxxxxxxxxxxxxxxxxxx+++++xXXXXXXXxxxxxxxxxxxxxxxxxxxxxxxxxxxXX$$$$$&&&&$$XXXXXXXXXXXxxxxxxxxxxxxxxxxxxxxxxxXXXX$XXxx+xxxxxxxxxXXXXXXXXXXX$$$$$XXXX$$XXX$$XXXXXXXXXXXXXXXXXXXXXXXXXXx
+++++++++++;;;:;;;::::::;;;;;;;;++;++++++++++;X$XX$$XXX$&&&$$$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&X$$x;;:::::...:;;+xxxxxX$$$$$&&&&&&&&&&&&&&$$$$XXXXXxx++;;;;;;;;;;++++++++x+++x++++++++xxxxxxxxxxxxxxxxxxxxxxxx+xx++++XXXXXXXXxxxxxxxxxxxXxxxxxxxxxxxxxxxxXXX$$$XX&&&$XXXXXXXXXXXxxxxxxxxxxxxxxxxxxxxxxxXXXXxXXxxxxxxxxxxxXXXXXXXX$X$$$$$$$$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
;;;;++;+++;;;++++++;;;;;;+++;;;;;;;;++++++++++;;;+X$$$$$$&&&&$$$&&$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$X$$;;:;:::::....::+xxxxxXX$$$$$$$$$$$$$$$XXXXXXxxxxxxxx+++++;+;;;;;++;++++++++++++++++++xxxxxxxx+xxxxxxxxxxxxxxxxxxxxxxxXXXXXXXXXxxxxxxxxXXxXxxxxxxxxxxxxxxxxXXX$$$$$$$&XXXXXXXXXXXXXxxxxxxxxxxxxxxxxxxxxxXXXX+x+x+xXxxXxXXXXXXXXX$$$$$X$X$X$$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx+
xxxxxxxx+x+++++x+x++++xx+++xx;++xxxxxxxxxxxxxxxxx+XXXX$$$&&&&$X&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$&&&&&&&&&&&&&&&&$&&&&&&&&&&&&&$$&$x+;:;;;;:;;;+;;++xxXXXXXXXXXXXxxxxxxXxxxxxxxxxxxxxxxxxx+;;;;;+++++xx+++xx+xx++++xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxXXXXXXxxxxxxxxxXXXXXXxxxxXxXxxxxxxxxXxxxXXX$$$$$XXXXXXXXXXXxxxxxxxxxxxxx+++++++xxxxx+++++++xXxXXXXXXXXXXX$$$$$$$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxXxx`;
//  tealcar.js
//  
//
//  Created by Tymon Wójcik on 26/08/2026.
//

